### ISSUE TITLE
2017 is more commonly said as "twenty seventeen" in English

### ISSUE THREAD

**Issue by OddBloke** [savoirfairelinux/num2words#141]
### Expected Behaviour

2017 formatted as "twenty seventeen"

### Actual Behaviour

2017 formatted as "two thousand and seventeen"

### Steps to reproduce

* `num2words(2017, to="year")`

**Comment by Goorzhel** [comment]
An argument can be made for both, but most of the results of my Googling support "twenty" (exhibits [A](http://www.sfgate.com/news/article/2010-Twenty-ten-vs-two-thousand-ten-3276950.php) and [B](https://english.stackexchange.com/questions/5442/what-are-the-rules-for-pronunciation-of-years-in-english)) over "two thousand" (exhibit [C](http://www.englishnumber.com/years/how-to-say-years-in-english.html)).

So, 👍 . Starting work on a patch.

**Comment by OddBloke** [comment]
Thanks!
