### ISSUE TITLE
Spanish language problem

### ISSUE THREAD

**Issue by jman27182818** [savoirfairelinux/num2words#146]
### Expected Behaviour

>>> num2words(72001720000000,lang='es')
u'setenta y dos billones un mil millones setecientos veinte millones'

### Actual Behaviour

>>> num2words(72001720000000,lang='es')
u'setenta y dos billones mil setecientos veinte millones'

### Steps to reproduce

* install num2words using pip install num2words
* go to python shell
* type num2words(72001720000000,lang='es')

**Comment by erozqba** [comment]
Works as expected!

Hi @jman27182818 
The actual behavior is correct and `72001720000000` should be written as `setenta y dos billones mil setecientos veinte millones`.
