### ISSUE TITLE
NL currency conversion fails

### ISSUE THREAD

**Issue by kvdb** [savoirfairelinux/num2words#159]
### Expected Behaviour

num2words(1.00, to='currency', lang='nl')
u'\xe9\xe9n euro, nul cent'

 ### Actual Behaviour

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv22545/local/lib/python2.7/site-packages/num2words/__init__.py", line 92, in num2words
    return getattr(converter, 'to_{}'.format(to))(number, **kwargs)
  File "/tmp/venv22545/local/lib/python2.7/site-packages/num2words/lang_NL.py", line 139, in to_currency
    longval=longval)
TypeError: to_currency() got an unexpected keyword argument 'longval'

### Steps to reproduce

import num2words
num2words(1.00, to='currency', lang='nl')

**Comment by shulcsm** [comment]
Sadly NL doesn't have new behavior implemented. You can try passing old=True for old one.
Assuming it has correct to_cardinal implementation i can try fixing it if you provide some test cases:

```
thirty-eight dollars and 40 cents
zero dollars and 00 cents
one dollar and one cent
four thousand, seven hundred and seventy-eight US dollars and zero cents
four thousand, seven hundred and seventy-eight dollars and zero cents
```

And gettext forms for EUR and currencies you want.

**Comment by kvdb** [comment]
thirty-eight dollars and 40 cents
achtendertig euro en 40 cent (it's custom not to write 'euros' or 'cents'. That'd be only used when counting physical euro coins - more on that here: https://onzetaal.nl/taaladvies/euro-euros/)

zero dollars and 00 cents
nul euro

one dollar and one cent
één euro en één cent

four thousand, seven hundred and seventy-eight US dollars and zero cents
vierduizendzevenhonderdachtenzeventig euro

I'm not sure how to properly translate the dollars, so I'm using euro.
Hope this is enough information for you to work with? Thanks for taking the time to implement this.
