### ISSUE TITLE
Py3.3 canot run

### ISSUE THREAD

**Issue by Alexey-T** [savoirfairelinux/num2words#16]
Py3.3 embedded, for editor like Sublime text (so I cannot use Py3.4), cannot run. Err on importing num2words. 

```
File "num2words\lang_EN.py", line 50
def merge(self, (ltext, lnum), (rtext, rnum)):
SyntaxError: invalid syntax
```

**Comment by prashanthmadi** [comment]
I have similar issue with python 3.5

Does this library supports 3.X ?

**Comment by michelpf** [comment]
Its seems to be an issue with PIP repository, maybe. In order to work, first clone the project in any folder, then, copy the content of num2words/num2words to Lib/site-packages/num2words/. Worked fine to me.

**Comment by erozqba** [comment]
Yes, this library supports Python 3.X. We run all the test against 3 different versions of Python using Travis-CI, you could check it at https://travis-ci.org/savoirfairelinux/num2words
I have tested it in Python 3.5 and after install num2words using PIP I can use the library without problems. Could you provide more information?

**Comment by erozqba** [comment]
I'm closing this, you are free to open it again if you have the same problem.
