### ISSUE TITLE
s/centavos/céntimos in Spain

### ISSUE THREAD

**Issue by carlosdauden** [savoirfairelinux/num2words#163]
https://github.com/savoirfairelinux/num2words/blob/551a980e544407c618a18c8e29eeb7f40fc013f0/num2words/lang_ES.py#L169

Cents are called "céntimos" in Spain

**Comment by erozqba** [comment]
@carlosdauden It's not so simple, you could check more information here http://lema.rae.es/dpd/srv/search?id=CkZrTrMPBD6tEznmYJ

**Comment by carlosdauden** [comment]
Según ese enlace:
"no son intercambiables: la fracción centésima de cada moneda tiene oficialmente uno de estos dos nombres"

Por lo que sí que es simple:
`hightxt, lowtxt = "euro/s", "céntimo/s"`

**Comment by erozqba** [comment]
This is already fixed https://github.com/savoirfairelinux/num2words/blob/88206811696433887b615e69cffde907fabc5fc8/num2words/lang_ES.py#L26

**Comment by carlosdauden** [comment]
Thanks
