### ISSUE TITLE
adding czech language to pypi

### ISSUE THREAD

**Issue by graymauser** [savoirfairelinux/num2words#168]
Hello,
would you consider updating current master to pypi? 
I'm using the Czech language specifically (it was a lifesaver to find it here). Now I'm moving to deployment and I really dont want users to have to manually download and install packages from github (target are people untouched by command-line).

Thanks
Best regards

**Comment by mrodriguezg1991** [comment]
@graymauser Sorry for all the issues related to this, a new version was deployed and we will continue to update the library in the future
