### ISSUE TITLE
Problem to write MILLIONS in num2words for fr (French)

### ISSUE THREAD

**Issue by lattoh** [savoirfairelinux/num2words#173]
Dear,
I use num2words 0.5.6 to convert in fr (French)

Num2words write " DEUX MILLION", for convertion of 2 000 000 in French, and that is not correct. It must write "DEUX MILLIONS"

I need your help to resolve this issue.

Best regards,

**Comment by ventilooo** [comment]
@lattoh thanks for your reports,

Would you like to submit a patch for this bug ?
:smiley:

**Comment by crazymerlyn** [comment]
I am unable to reproduce this bug. Does it still exist?

**Comment by erozqba** [comment]
Works as expected on the master branch.
