### ISSUE TITLE
Korean support

### ISSUE THREAD

**Issue by BayMinimum** [savoirfairelinux/num2words#209]
Hello! I just found this wonderful project and wish if there's support for my language :crying_cat_face: If no one is doing it, can I work on implementing Korean numbers?

**Comment by erozqba** [comment]
Hello @BayMinimum!
Yes please, implement Korean support :pray: all pull request are welcome.
Thanks a lot in advance.

**Comment by erozqba** [comment]
@zenogantner thanks!
