### ISSUE TITLE
Include license files in the pypi tarball

### ISSUE THREAD

**Issue by williamjmorenor** [savoirfairelinux/num2words#21]
Hi

I am packaging num2words in Fedora, I see you are using the GPL license but you do not include the license file in the pypi tarball, can you please add the sile so I have not to patch your app at the moment of create the rpm

**Comment by cormier** [comment]
Hi William,

Thank you very much for packaging num2words in Fedora. I will add a copy 
of the licence soon or you can submit a pull request in the meantime if 
you wish.

David
