### ISSUE TITLE
Move test files from /site-packages/test 

### ISSUE THREAD

**Issue by williamjmorenor** [savoirfairelinux/num2words#22]
Hi

Just a question, python-num2words is placing tests files under the root directory of python site-packages, I can not include this files in the rpm, I will exclude this files but It could be nice to move remane the tests directory to num2words-test or something similar so I will can include this files in furete versions of the package.

https://bugzilla.redhat.com/show_bug.cgi?id=1223623

**Comment by williamjmorenor** [comment]
num2words have packaged:

https://admin.fedoraproject.org/pkgdb/package/python-num2words/

**Comment by hsoft** [comment]
Oh, I think I misunderstood the bug report initially and underestimating its severity. Polluting site-packages is bad, thanks for letting us know. I'll try to fix this ASAP.

Also, thanks for your packaging efforts!

**Comment by hsoft** [comment]
## Reproduction notes

If we install num2words in an env with `python setup.py install`, the whole package will be bundled in a `.egg`, so it won't reproduce the bug.

To reproduce the bug, one has to do `pip install .` when being at the root of num2words' repo.

**Comment by williamjmorenor** [comment]
Thanks for that, python-num2words have been packaging without the test files, if you fix that please make a new release to pypi and I will update the packge, I will request the epel branch to make python-num2words avalibe for RHEL/CentOS and others, at less for epel 7 release.

**Comment by hsoft** [comment]
Fixed. Can you confirm that it also work on your local machine? If it works for you, I'll make a release.

Watch out for stale egg-info files, which will falsely install tests (see http://stackoverflow.com/a/26547314/103667 ). I wasted most of my time on that...

**Comment by williamjmorenor** [comment]
I apply the pacht in rpmbuild and work, there is not tests directory in site-packages both for python 2 and 3.

Please if you push the new version will be great if you inlude the license file in the pypi tarball in #21 

Sorry bug Fedora Packaging Guidelines requires to include the test files in the package, even rpm have a especial treatment with the %license macro

**Comment by hsoft** [comment]
Alright, thanks. Good idea about #21. I'll do that.

**Comment by hsoft** [comment]
It's uploaded to PyPI, let me know if packaging is still problematic.
