### ISSUE TITLE
Failed build with python3.6

### ISSUE THREAD

**Issue by wenheping** [savoirfairelinux/num2words#229]
Hi,

   I failed build num2words-0.5.8 with python-3.6 on FreeBSD-11.2, while 2.7 and 3.7 success.
   The error message is : 
  =======================<phase: configure      >============================
===>   py36-num2words-0.5.8 depends on package: py36-setuptools>0 - found
===>   py36-num2words-0.5.8 depends on file: /usr/local/bin/python3.6 - found
===>   py36-num2words-0.5.8 depends on file: /usr/local/bin/ccache - found
===>  Configuring for py36-num2words-0.5.8
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 20, in <module>
    LONG_DESC = open('README.rst', 'rt').read() + '\n\n' + \
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1557: ordinal not in range(128)
*** Error code 1

Any suggestions ?

wen

**Comment by null-git** [comment]
Hi, I'm the maintainer of this port.

The break occured in the 0.5.8 release, 0.5.7 build fine on python 3.6.
The character in question seems to be the 'é' in line 50 in README.rst, so it seems to be some kind of encoding error. But why it only happens on python 3.6 and only in this version of the library I can't say.

Anyway, opening all files in setup.py with encoding='utf-8' set fixes the problem.

**Comment by erozqba** [comment]
@null-git I will also suggest removing the problematic example on the README.rst file

```
diff --git a/README.rst b/README.rst
index d9f4cd2..8e509c1 100644
--- a/README.rst
+++ b/README.rst
@@ -46,8 +46,6 @@ Command line::
 
     $ num2words 10001
     ten thousand and one
-    $ num2words 10123123 --lang es
-    diez millones ciento veintitrés mil ciento veintitrés
     $ num2words 24,120.10
     twenty-four thousand, one hundred and twenty point one
     $ num2words 24,120.10 -l es

```

I have created a PR #231 to try to fix this problem. Can you test this branch and provide some feedback?

**Comment by null-git** [comment]
Could we have a new release to include this fix?

**Comment by erozqba** [comment]
@null-git sure, I will prepare one as soon as possible.
