### ISSUE TITLE
issue after converting number to words

### ISSUE THREAD

**Issue by tien-le** [savoirfairelinux/num2words#24]
Hi,

Thanks for your lib that helps me so much to convert number to words. But, I have some following issues:

>>> num2words(12.50, ordinal=False, lang='en')
u'twelve point five zero'

>>> num2words(12.51, ordinal=False, lang='en')
u'twelve point five zero'
>>> num2words(12.52, ordinal=False, lang='en')
u'twelve point five one'
>>> num2words(12.53, ordinal=False, lang='en')
u'twelve point five two'
>>> num2words(12.54, ordinal=False, lang='en')
u'twelve point five three'

>>> num2words(12.55, ordinal=False, lang='en')
u'twelve point five five'
>>> num2words(12.56, ordinal=False, lang='en')
u'twelve point five six'
>>> num2words(12.57, ordinal=False, lang='en')
u'twelve point five seven'
>>> num2words(12.58, ordinal=False, lang='en')
u'twelve point five eight'

>>> num2words(12.59, ordinal=False, lang='en')
u'twelve point five eight'

Can you help me to tackle them?
Thanks a lot!
Best regards,
Tien

**Comment by hsoft** [comment]
Float numbers are fundamentally imprecise. Did you try using `Decimal` instead?

**Comment by isnani** [comment]
@hsoft
I changed the way you read the number behind the point. IMHO, we should only consider the digit we see and spell it as is.
