### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Kangcor** [savoirfairelinux/num2words#249]
Could you please tag and publish a new release? Thanks

**Comment by ventilooo** [comment]
@erozqba Could you do this in the following days ?

**Comment by Kangcor** [comment]
Is there any estimation for the release date?

**Comment by Alexandre-Bernardes** [comment]
Cool, I'll be very gratetul too!
Thanks a lot!

**Comment by erozqba** [comment]
I have made the release v0.5.10. 
https://pypi.org/project/num2words/
https://github.com/savoirfairelinux/num2words/releases/tag/v0.5.10

**Comment by Alexandre-Bernardes** [comment]
thank you!

**Comment by Kangcor** [comment]
Thanks!
