### ISSUE TITLE
Num2words Doesn't change the currency based on country name

### ISSUE THREAD

**Issue by sekti92** [savoirfairelinux/num2words#267]
Why the currency still in Euro currency even i have changed the language?
Is there anything that I need to change to use this library? Thanks. 

### Expected Behaviour

>>> num2words(25502.51, to='currency', lang='en')
'twenty-five thousand, five hundred and two dollars, fifty-one cents'
>>> num2words(25502.51, to='currency', lang='en_GB')
'twenty-five thousand, five hundred and two pounds, fifty-one pence'

### Actual Behaviour
>>> num2words(2550251,to='currency',lang='en')
'twenty-five thousand, five hundred and two euro, fifty-one cents'
>>> num2words(2550251,to='currency',lang='en_GB')
'twenty-five thousand, five hundred and two euro, fifty-one cents'

**Comment by priyadhoundiyal** [comment]
I'm also facing the same problem on setting lang to 'en_IN'

**Comment by erozqba** [comment]
```
num2words('38.4', lang='en', to='currency', separator=' and', cents=False, currency='USD')
"thirty-eight dollars and 40 cents"
```

For other examples, please check the tests
https://github.com/savoirfairelinux/num2words/tree/master/tests
