### ISSUE TITLE
Incorrect translation of numbers in Polish

### ISSUE THREAD

**Issue by warp3r-68** [savoirfairelinux/num2words#304]
### Expected Behaviour
IN FILE: num2words/lang_PL.py
TWENTIES = {
    2: ('dwadzieścia',),
    3: ('trzydzieści',),
    4: ('czterdzieści',),
    5: ('pięćdziesiąt',),
    6: ('sześćdziesiąt',),
    7: ('siedemdziesiąt',),
    8: ('osiemdziesiąt',),
    9: ('**dziewięćdziesiąt**',),
}

IN FILE: num2words/tests/test_pl.py
**dziewięćdziesiąt**

### Actual Behaviour
IN FILE: num2words/lang_PL.py
TWENTIES = {
    2: ('dwadzieścia',),
    3: ('trzydzieści',),
    4: ('czterdzieści',),
    5: ('pięćdziesiąt',),
    6: ('sześćdziesiąt',),
    7: ('siedemdziesiąt',),
    8: ('osiemdziesiąt',),
    9: ('**dziewięćdzisiąt**',),
}

IN FILE: num2words/tests/test_pl.py
**dziewięćdzisiąt**

**Comment by cyriaka90** [comment]
see also: https://github.com/savoirfairelinux/num2words/issues/277

**Comment by cyriaka90** [comment]
fixed with https://github.com/savoirfairelinux/num2words/pull/345 :)

**Comment by mrodriguezg1991** [comment]
@warp3r-68 @cyriaka90 Can you test this issue in order to validate it and close ? 
Thanks
