### ISSUE TITLE
Can I change the word euros for soles (peruvian currency) or simple not show it?

### ISSUE THREAD

**Issue by OmarGonD** [savoirfairelinux/num2words#305]
### Expected Behaviour

`num2words(1670.60, to='currency', lang='es')`

Should return;

`mil seiscientos setenta soles con sesenta céntimos`

or not show the type of currency at all.

`mil seiscientos setenta con sesenta céntimos`

### Actual Behaviour

`mil seiscientos setenta euros con sesenta céntimos`

### Steps to reproduce

```
from num2words import num2words
num2words(1670.60, to='currency', lang='es')
```

**Comment by erozqba** [comment]
@OmarGonD yes you can, you can override the currency type like this:
```
>>> num2words(1670.60, to='currency', lang='es', currency='PEN')
'mil seiscientos setenta soles con sesenta céntimos'
```
