### ISSUE TITLE
Implement Norwegian language support

### ISSUE THREAD

**Issue by orjanv** [savoirfairelinux/num2words#32]
Hi, I have started translating the german version into norwegian, but not entirely sure what everything is and what to translate. Is there a language guide I could follow?

**Comment by hsoft** [comment]
Hi @orjanv, thanks for getting into this. Unfortunately, no, there's not much of a guide for implementing a new language. It's mostly a process of choosing the closest language, base yourself on it, and do a game of trial and error. I'm sorry that it's not easier than that...

**Comment by erozqba** [comment]
@orjanv you are still implementing Norwegian language support? PR is welcome.

**Comment by zenogantner** [comment]
There is now Norwegian support ("no"). Can this be closed?

**Comment by erozqba** [comment]
Yes, thanks @zenogantner
