### ISSUE TITLE
u before result

### ISSUE THREAD

**Issue by CILP** [savoirfairelinux/num2words#34]
Hi,

Alway shows the 'u' vowel at the start of each result, is it normal?

>>> num2words(111999, lang='es')
u'ciento once mil novecientos noventa y nueve'

**Comment by Arrowana** [comment]
In means that the string as been represented as unicode, no harm

http://stackoverflow.com/questions/11279331/what-does-the-u-symbol-mean-in-front-of-string-values

**Comment by hsoft** [comment]
Thanks @Arrowana
