### ISSUE TITLE
Danish language support?

### ISSUE THREAD

**Issue by fennesz** [savoirfairelinux/num2words#39]
Is anyone doing Danish language support?

**Comment by hsoft** [comment]
I don't think so. You're interested in doing it @fennesz ?

**Comment by fennesz** [comment]
@hsoft 
Yes. :)
I've forked the project, and will begin working on it.

**Comment by fennesz** [comment]
Since the Danish number system is quite unusual (Refer to this SATW comic: http://satwcomic.com/just-a-number )...

Danes out there who want to lend a hand implementing Danish for num2words, the fork I'm working on can be found here: https://github.com/fennesz/num2words

**Comment by erozqba** [comment]
thanks @zenogantner
