### ISSUE TITLE
Arabic: Connector word (و) is missing if the number has zero in the one's digit

### ISSUE THREAD

**Issue by adilmujeeb** [savoirfairelinux/num2words#391]
### Expected Behaviour

مائة و ثلاثون

### Actual Behaviour

مائةثلاثون

### Steps to reproduce

The connector word (و) is missing if the number has zero in the one's digit.
For example, 130 will give (مائةثلاثون) when it should be (مائة و ثلاثون)

**Comment by smali261** [comment]
I saw this issue .to fix this we need to change one line in lang.ar file.
But I am new on this framework, how I can update this file.
