### ISSUE TITLE
Conversion Bug

### ISSUE THREAD

**Issue by Pr-World** [savoirfairelinux/num2words#432]
### Expected Behaviour

`>> num2word.word(120000455)`
`'One Hundred Twenty million Four Hundred Fifty Five'`

### Actual Behaviour

`>> num2word.word(120000455)`
`'One Hundred Twenty million  thousand Four Hundred Fifty Five'`

### Steps to reproduce

* step 1 : `>> num2word.word(120000455)`
* step 2 : done

### Other possible bugs when it happens
* #### It happens if we leave the thousands, million or billion place all 000
* #### Ex 1: `>>> num2word.word(1000000233)`
* #### Ex 2: `>>> num2word.word(1000000000255)`

**Comment by Pr-World** [comment]
### If you are wondering what's wrong:
#### The `thousand` comes from nowhere. try `num2word.word(10000000002)` there are unwanted `million` and `thousand`

**Comment by eugene-k** [comment]
Wrong place to send - this is num2words project, not num2word.
