### ISSUE TITLE
floating point?

### ISSUE THREAD

**Issue by johnmudd** [savoirfairelinux/num2words#44]
Doesn't seem to support floating point well.

    >>> num2words(111.3)
    u'one hundred and eleven point two nine'
    >>> num2words(.1234)
    u'zero point one two'

**Comment by nicolls1** [comment]
Just had this as well
```
>>> num2words.num2words(55.55)
u'fifty-five point five four'
```

**Comment by hsoft** [comment]
Please see issue #1
