### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by eagleoflqj** [savoirfairelinux/num2words#450]
Great project, thank you.
I want to use it in [SymPy Beta](https://github.com/eagleoflqj/sympy_beta), which runs on [pyodide](https://github.com/pyodide/pyodide). However, as num2words currently support python 2 and 3, its dependency of docopt cannot be switched to docopt-ng, which is a better-maintained fork of docopt and supports python 3 only. Pyodide can only load a pure python 3 wheel.
To fulfill my requirement, I'm going to copy the files I need from num2words and maintain them myself, but I think num2words dropping python 2 support and upgrading dependency is a better choice.
What do you think?

**Comment by mrodriguezg1991** [comment]
We won't be supporting python 2 in the upcoming versions of the application, and all python 2 uses will be eventually remove
