### ISSUE TITLE
Hebrew update

### ISSUE THREAD

**Issue by eyaler** [savoirfairelinux/num2words#491]
Features:
* change spelling from biblical and short-form (ktiv haser) to modern long-form (ktiv male)
* male/female genders (default to female for cardinal and to male for ordinal)
* ordinals (with optional definite form)
* decimal fractions and negatives
* fix currency name (NIS->ILS), add currency genders, pluralize סנט, add optional singular forms for plural when allowed.
* fix word order for singular form with currency
* fix "two" to always use construct form with currency
* construct forms (סמיכות)
* max val = 1e66 (up from 10,000)

Implemented in https://github.com/savoirfairelinux/num2words/pull/490

**Comment by mrodriguezg1991** [comment]
already merged, thanks for your contribution
