### ISSUE TITLE
Version on pypi.python.org outdated

### ISSUE THREAD

**Issue by mbcosta** [savoirfairelinux/num2words#50]
Hi
   The version in https://pypi.python.org/pypi/num2words seems outdated. If install with pip
when the program try to use the pt_BR, I got this error

    from num2words.lang_PT_BR import Num2Word_PT_BR
ImportError: No module named lang_PT_BR

But if I clone this repo and install works fine.

**Comment by cantoniazzi** [comment]
I had the same problem.

**Comment by hsoft** [comment]
Sorry for the delay. I've been very busy. I made a new release at https://pypi.python.org/pypi/num2words/0.5.4
