### ISSUE TITLE
Library don't work with Ukrainian float numbers

### ISSUE THREAD

**Issue by techn0man1ac** [savoirfairelinux/num2words#579]
Hello.

I have are problem - here simple example:

```Python
import num2words 

text = 'Правило Парето, це завжди 70% на 30% - 30.0% це робота а 70.0% - результат'
text = text.replace("%", " %") # 89.9% -> 89.9 %
text = ' '.join([num2words.num2words(i, to='cardinal', lang='uk') if i.isdigit() else i for i in text.split()])

print(text) # Правило Парето, це завжди сімдесят % на тридцять % - 30.0 % це робота а 70.0 % - результат
```

As you can see, everything works perfectly with integers, but misses floating point numbers.

**Comment by smilingDima** [comment]
`"30.0".isdigit()` returns False.
You can try comething like this:
```
text = ' '.join([num2words.num2words(i, to='cardinal', lang='uk') if i.replace('.','',1).isdigit() else i for i in text.split()])
```
The result is:
Правило Парето, це завжди сімдесят % на тридцять % - тридцять кома нуль нуль % це робота а сімдесят кома нуль нуль % - результат

**Comment by techn0man1ac** [comment]
> `"30.0".isdigit()` returns False. You can try comething like this:
> 
> ```
> text = ' '.join([num2words.num2words(i, to='cardinal', lang='uk') if i.replace('.','',1).isdigit() else i for i in text.split()])
> ```
> 
> The result is: Правило Парето, це завжди сімдесят % на тридцять % - тридцять кома нуль нуль % це робота а сімдесят кома нуль нуль % - результат

Awesome. Thank's.
