### ISSUE TITLE
How to use num2words with currency?

### ISSUE THREAD

**Issue by bataak** [savoirfairelinux/num2words#63]
Is there any option to use num2words with currency?

**Comment by dufresnedavid** [comment]
@bataak no, it has not. The use case for this library is to print amounts on checks. I've never seen a check where the currency is printed with the amount in words. If you need that, why dont you concat the result of num2words with your currency code ?

**Comment by bataak** [comment]
Thanks for your quick reply. I mean, can I use`num2words(1234.56, ??)` then it'll print `one thousand two hundred thirty-four dollars`.  Actually I don't know the option, but I found currency related syntax in your code.

**Comment by dufresnedavid** [comment]
@bataak I confirm that you cannot do this with this library.

**Comment by dufresnedavid** [comment]
@bataak in fact, the code for converting to currencies exists. This is old code that was not actually maintained. It is not supported by the num2words.num2words wrapper function. This was written by the previous maintainer of the library (not Savoir-faire Linux).

Howerver, if you wish to add the support for currencies, this could be done. This would need to be tested with unit tests.

**Comment by bataak** [comment]
I see. Thanks for you reply.

**Comment by erozqba** [comment]
Hi @bataak 
I have made a PR #95 to make easier the use of other converters, so it should be easier after this change has been merged.

**Comment by bataak** [comment]
Wow, that's great!

**Comment by erozqba** [comment]
Fixed in #95
