### ISSUE TITLE
Vietnam lang  conversion is wrong !

### ISSUE THREAD

**Issue by hoan024** [savoirfairelinux/num2words#69]
in Vietnam lang :
145**001**000 read correctly is : "một trăm bốn lăm triệu **không trăm lẻ** một ngàn"
you can fix it :)
+> test case wrong :
self.assertEqual(num2words(523056, lang="vi_VN"), "năm trăm hai mươi ba nghìn năm mươi sáu")
+> fix right :  self.assertEqual(num2words(523056, lang="vi_VN"), "năm trăm hai mươi ba nghìn **không trăm** năm mươi sáu")

P/S : sorry my english is bad !

**Comment by erozqba** [comment]
@hoan024, thanks for taking the time to create the issue, pull request are welcome, I don't speak Vietnam so we really trust in all people making contributions.

**Comment by anothingguy** [comment]
@hoan024: it's not wrong, but it's not perfect yet, i've known this issue at initial commit for VietNam lang. It was just initial commit. At that time, i don't have time to handle special case for **không trăm** or **không trăm lẻ**.

523056 = `năm trăm hai mươi ba nghìn năm mươi sáu`. It's acceptable for us, right ?. Actually, **không trăm** is not very important here. Although i agree that: `năm trăm hai mươi ba nghìn **không trăm** năm mươi sáu` would be perfect for us.

but as @erozqba said: we should improve it day by day and any PR are welcome.
I will try to continue improve it in future if it's not improved yet.

thanks @erozqba for your reply :D.
Regards.
