### ISSUE TITLE
"one hundred, ninety-eight" vs. "one hundred ninety-nine"  vs. "one hundred and ninety-eight"

### ISSUE THREAD

**Issue by laowantong** [savoirfairelinux/num2words#8]
Comparing the outputs of Taro Ogawa's original library (namely num2word_EN.to_card) and yours, I found some recurring discrepancies:

```
one hundred and ninety-eight
one hundred, ninety-eight (the "and" is replaced by a comma)

one hundred and ninety-nine
one hundred ninety-nine (the "and" is suppressed)

two hundred and ninety-eight
two hundred, ninety-eight

two hundred and ninety-nine
two hundred, ninety-nine

...
```

Taro Ogawa's gives the expected result (21124) on the 17th problem of the Projet Euler: http://projecteuler.net/problem=17. Yours give 21070. Using `lang="en"` or `lang="en_GB"` makes no difference.

**Comment by Valsept** [comment]
I was a good story indeed.
